[settings]
yes = true

[tools]
eza = "latest"
uv = "latest"
neovim = "0.10.4"
flutter = "3.22.3"
jq = "latest"
tmux = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
bottom = "latest"
yq = "latest"
node = "latest"

[tasks.setup]
run = [
  "npm i -g bash-language-server",
  "cargo install --features lsp --locked taplo-cli",
  "cargo install oxi",
]


