[settings]
yes = true

[tools]
eza = "latest"
uv = "latest"
neovim = "0.11.5"
flutter = "3.22.3"
jq = "latest"
tmux = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
bottom = "latest"
yq = "latest"
node = "latest"
lazygit = "0.57.0"
rust = "1.92.0"
python = "3.13.11"
ollama = "latest"

[env]
AI_MODEL="gpt-oss:20b"
OLLAMA_API_BASE="http://127.0.0.1:11434"

[shell_alias]
aider="uv run aider --model ollama/$AI_MODEL --chat-language japanese"

[tasks.install]
run = "mise install"

[tasks.bootstrap-nvim]
depends = ["install"]
run = [
  "npm i -g bash-language-server",
  "cargo install --features lsp --locked taplo-cli",
  "cargo install oxi",
]

[tasks.bootstrap-ai]
depends = ["install"]
run = [
  "uv pip install --python .venv/bin/python -U aider-chat",
  "uv pip install --python .venv/bin/python -U audioop-lts",
  "uv pip install --python .venv/bin/python -U 'litellm[all]==1.75.6'",
]


