[settings]
yes = true

[tools]
eza = "latest"
uv = "latest"
neovim = "0.11.5"
flutter = "3.38.9"
jq = "latest"
tmux = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
bottom = "latest"
yq = "latest"
node = "latest"
lazygit = "0.57.0"
rust = "1.92.0"
python = "3.13.11"

[env]
EDITOR="nvim"

[shell_alias]
ls="eza"
la="eza -la"
vi="nvim"

[tasks.setup]
run = """
  mise install
  cd $HOME
  tpm_dir="$HOME/.tmux/plugins/tpm"
  if [ ! -d $tpm_dir ]; then
    git clone https://github.com/tmux-plugins/tpm $tpm_dir
    tmux source ~/.tmux.conf
  fi
"""

[tasks.nvim]
run = [
  "npm i -g bash-language-server tree-sitter-cli",
  "cargo install --features lsp --locked taplo-cli",
  "cargo install oxi",
]
